### ISSUE TITLE
Question about data preparing

### ISSUE THREAD

**Issue by Runsong123** [kyleleey/RICO#3]
Dear author,

Congrats for your great work!
May I ask you for the details about the data preparing since I want to apply your methods to my captured data? Specifically, I am curious about the "instance_id.json" file and how to keep the generated label multi-view consistent. For example, how to make sure the id:4 is the always point to the sofa_2 from different viewpoints in data.

![image](https://github.com/kyleleey/RICO/assets/39645074/a0edfa77-71da-463d-910f-6adc75b1a9d3)

Bests,
Runsong

**Comment by kyleleey** [comment]
Hi Runsong,

Sorry for the late reply. Unfortunately I used the dataset with multi-view consistent instance ID labels, like ScanNet / Replica, etc. In my synthetic scenes I also used Blender to create consistent instance labels.

As I'm also working on some extensions of this work and what I have in mind about data preprocessing on real data, is to combine some mask from off-the-shelf model ([GroundingDINO](https://github.com/IDEA-Research/GroundingDINO)) and a recent nerf-based method to combine multi-view inconsistent segmentations together ([Panoptic-Lifting](https://github.com/nihalsid/panoptic-lifting)).

Hope this can answer your question.
