### ISSUE TITLE
mono_prob variable is not defined in the get_depth_loss and get_normal_loss (Maybe a code bug)

### ISSUE THREAD

**Issue by DaLi-Jack** [kyleleey/RICO#4]
Hi, Congrats for your great work!
I found that there may be a bug in the [mono_prob variable defined in lines 448-454 of the loss.py file](https://github.com/kyleleey/RICO/blob/b1a4ae651db965435feeb7d3a59ec25e614ad6d3/code/model/loss.py#L448C58-L448C58).
Because the mono_prob variable is not defined in the get_depth_loss and get_normal_loss functions.
I would be grateful for any help you can provide!

**Comment by kyleleey** [comment]
Hi Junfeng,

Thanks a lot for finding this! Yes this is a code bug, just some parameters and design I tried before and haven't been fully cleaned before.

I have updated the [loss.py](https://github.com/kyleleey/RICO/blob/main/code/model/loss.py), please inform me if you encounter any other problems
