### ISSUE TITLE
Why you use Neus sample method instead of VolSDF sample method like MonoSDF

### ISSUE THREAD

**Issue by DaLi-Jack** [kyleleey/RICO#5]
Hi, Congrats for your great work!
I noticed that your code refers to the MonoSDF code, 
but you use Neus sample method instead of VolSDF sample method like MonoSDF for ray sampling. 
Could you let me know if there is any special reason for doing this? 
I would be grateful for any help you can provide!

**Comment by kyleleey** [comment]
Hi Junfeng,

This is a good question. And my experience from many projects is these two ways of volume rendering SDF have their own effects. And this may also related to their different implementation of sampling / eikonal loss.

In this work I find the NeuS pipeline works better with my proposed losses. In detail, it have much less floaters / irrelevant structures.

In general people concern NeuS volume rendering as more "unbiased" comparing to VolSDF. And there are also many more SDF volume rendering methods been proposed. You may check this [project](https://github.com/DavidXu-JJ/DebSDF) for a most recent one.

**Comment by DaLi-Jack** [comment]
I see! Thank you very much for your patient answer!
