### ISSUE TITLE
Which scenes do you use for ScanNet?

### ISSUE THREAD

**Issue by Pixie8888** [kyleleey/RICO#7]
Hi,

Thanks for releasing code! I notice that you use 7 scenes from ScanNet, while objectsdf++ use 4 scenes. May I know is there any overlapped scenes that are used in the objectsdf++? I want to fairly compare with you and objectsdf++ using the same scene.

Also, how to evaluate on ScanNet? You only provide evaluation on synthetic dataset.

**Comment by kyleleey** [comment]
Hi,

You can check my [reply](https://github.com/kyleleey/RICO/issues/1#issuecomment-1670769823) in a previous issue. The last three scenes are overlapped, i.e. used in both objsdf and RICO.

I didn't do evaluation per-object on ScanNet, since it doesn't provide a high-quality overall geometry GT for each object. I only evaluate the surface reconstruction performance of the entire scene. This evaluation follows the common practice in [MonoSDF's evaluation](https://github.com/autonomousvision/monosdf#scannet)

**Comment by Pixie8888** [comment]
Thanks for your reply. Do you have per scene result on ScanNet?

By the way, when I run your code on ScanNet using 
```
python -m torch.distributed.launch --master_port=25641 training/exp_runner.py --conf confs/RICO_scannet.conf  --scan_id 1 --port 295
```
, I encountered this error:
![image](https://github.com/kyleleey/RICO/assets/72333326/0f86734c-dc81-49ea-8475-5635608ee61d)

Do you know how to solve it?

**Comment by kyleleey** [comment]
Hi, I'm not so sure the distributed training is supported in my current codebase (I know original MonoSDF codebase seems to support it but I have changed so many things on top of it). Maybe can you try to directly follow README's [instruction](https://github.com/kyleleey/RICO/tree/main#training) on running without SLURM?

Regarding the results for each scene. I think it requires some time for me to locate the individual results from my old experiments logs :) However you can check my [reply](https://github.com/kyleleey/RICO/issues/1#issuecomment-1670628219) in previous issue that I shared all the reconstructed meshes, you can compute their metrics using the evaluation script.

**Comment by Pixie8888** [comment]
Thanks! Do you know how to combine all of the part mesh into a complete scene mesh? You only provide each part of mesh:
![image](https://github.com/kyleleey/RICO/assets/72333326/a9ebc4ec-6bbe-4503-bfa9-7736e2ff2822)

**Comment by kyleleey** [comment]
Hi, sorry I didn't upload the entire scene results before. I just uploaded the reconstructed meshes for each ScanNet scene in this [link](https://drive.google.com/drive/folders/1fq6k56q7CU21KrAAJ9SUIQyhM2FvqmpT?usp=sharing). I think these results are the ones I used to compute metrics, i.e., the reconstruction results after TSDF-fusion post-processing.

**Comment by Pixie8888** [comment]
okay, thanks.
I have a question regarding eqn 9. Why use reversed depth instead of depth (if use depth, is it equivalent to D_o < D_b)? How to understand eqn 9?

**Comment by kyleleey** [comment]
Because the object has thickness. 

Reversed depth actually doesn't equal to (far - depth), reversed depth = far - depth - object_thickness

By regularizing the reversed depth I can regularize the object's invisible surface, i.e. regularize the entire thickness

**Comment by Pixie8888** [comment]
thanks!
