### ISSUE TITLE
Many floating artifacts in the air.

### ISSUE THREAD

**Issue by DaLi-Jack** [kyleleey/RICO#9]
Hi, Congrats for your great work!
But when I reproduced your code on the **Scannet scan6**, I found that there were many floating artifacts in the air. Why does this happen? And how to avoid this problem?
![a2d515ff21245ae2ca5f30ce1416ca6](https://github.com/kyleleey/RICO/assets/70205757/1a623e96-ed11-4bba-ad73-d8af494e0054)
I would be grateful for any help you can provide!

**Comment by DaLi-Jack** [comment]
And I think the background is also a little strange. [This link](https://drive.google.com/file/d/1YPSk1iRURmIjaSPEgD_TeNijjy7f7s9M/view?usp=sharing) contains the results I reproduced.
![image](https://github.com/kyleleey/RICO/assets/70205757/89497be3-7b68-41bf-8b6b-7c71e41beb23)
Looking forward to your reply!

**Comment by kyleleey** [comment]
Hi, I think the reason is:

In the preprocessing step, the world coordinates are transformed to a unit cube, i.e., all the camera poses are transformed, and the final marching cube is conducted in this cube. If I remembered correctly, the size of this unit cube is the maximum value of x, y, and z in all the original camera poses.

However, in this scene all the training views only cover a part of the cube, i.e. the floating areas are areas that haven't been optimized in the training, and never be observed in all training views.

**Comment by DaLi-Jack** [comment]
Hello, thanks for your reply.
These floating areas are places that are not observed from the input perspective, but the reconstructed scene I got using MonoSDF under the same input data is closed and does not have so many floating objects. In addition to the training views, what is the other problem? Is it also related to bg regularization or SDF transform method (NeuS or VolSDF)? You have a discussion about SDF and rendering method in supp (E.2. Backbone Ablation Study). Is there any conclusion on this issue at that time?

**Comment by kyleleey** [comment]
I think you're right. That's another reason. Before the unified framework SDFStudio came out, I used to try replacing VolSDF in MonoSDF to NeuS, and for the indoor scenes, the structures outside the room (unobserved in training) produced by two methods behave in a different way. NeuS would tend to have much more floating artifacts in the unobservable regions.

The difference includes:
1. implementation of eikonal loss
2. ray sampling
3. volume rendering transformation

I didn't do thorough ablation experiments after that, but NeuS and VolSDF would perform very differently in the unobservable regions.

**Comment by DaLi-Jack** [comment]
I see, thanks for your reply!
